# Generated by Django 3.1.7 on 2021-03-09 13:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 3, 9, 13, 1, 55, 631542, tzinfo=utc)
            ),
        ),
    ]
