# Generated by Django 3.1.7 on 2021-03-09 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_last_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
