# Generated by Django 3.1.7 on 2021-03-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_auto_20210309_2151"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="users"),
        ),
    ]
